volumes:
  ffun_postgres_data: {}
  ffun_frontend_data: {}
  ffun_caddy_data: {}
  ffun_caddy_config: {}
  ffun_local_ollama_data: {}

services:

  postgres:
    image: postgres:15.2
    volumes:
      - ffun_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ffun
      POSTGRES_USER: ffun
      POSTGRES_PASSWORD: ffun
    healthcheck:
      test: "pg_isready -U ffun -d ffun"
      interval: 1s
      timeout: 5s
      retries: 10

  local-llm:
    image: ollama/ollama:latest
    volumes:
      - ffun_local_ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/11434"]
      interval: 10s
      timeout: 3s
      retries: 12

  backend-api:
    image: tiendil/feeds-fun-backend:latest
    depends_on:
      postgres:
        condition: service_healthy
      local-llm:
        condition: service_started
    command:
      - /bin/bash
      - -c
      - |
        ffun migrate
        echo "migrations successed"
        uvicorn ffun.application.application:app --host 0.0.0.0 --port 8000 --workers 1
    volumes:
      - ${PWD}/ffun.env:/ffun/.env
      - ${PWD}/tag_processors.local-llm.toml:/ffun/tag_processors.toml
    environment:
      FFUN_ENABLE_API_SPA: "True"
      FFUN_LIBRARIAN_TAG_PROCESSORS_CONFIG: "/ffun/tag_processors.toml"
      FFUN_LOCAL_LLM_API_ENTRY_POINT: "http://local-llm:11434/v1"
      PYTHONOPTIMIZE: "1"

  backend-workers:
    image: tiendil/feeds-fun-backend:latest
    depends_on:
      postgres:
        condition: service_healthy
      local-llm:
        condition: service_started
    command:
      - /bin/bash
      - -c
      - |
        ffun migrate
        echo "migrations successed"
        ffun workers --loader --librarian
    volumes:
      - ${PWD}/ffun.env:/ffun/.env
      - ${PWD}/tag_processors.local-llm.toml:/ffun/tag_processors.toml
    environment:
      FFUN_LIBRARIAN_TAG_PROCESSORS_CONFIG: "/ffun/tag_processors.toml"
      FFUN_LOCAL_LLM_API_ENTRY_POINT: "http://local-llm:11434/v1"
      PYTHONOPTIMIZE: "1"

  frontend-data:
    image: tiendil/feeds-fun-frontend-data:latest
    volumes:
      - ${PWD}/ffun.env:/ffun/.env
      - ffun_frontend_data:/ffun-static-data

  frontend-caddy:
    image: caddy:2.10.0
    volumes:
      - ffun_caddy_data:/data
      - ffun_caddy_config:/config
      - ffun_frontend_data:/ffun-static-data
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend-api:
        condition: service_started
      frontend-data:
        condition: service_completed_successfully
